// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oid85.Athletic.Infrastructure;

#nullable disable

namespace Oid85.Athletic.Infrastructure.Migrations
{
    [DbContext(typeof(AthleticContext))]
    [Migration("20251218072806_AddPressureTable")]
    partial class AddPressureTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityAlwaysColumns(modelBuilder);

            modelBuilder.Entity("Oid85.Athletic.Infrastructure.Entities.ExerciseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("CountIterations")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExerciseTemplateId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Minutes")
                        .HasColumnType("integer");

                    b.Property<int?>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("TrainingId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Weight")
                        .HasColumnType("decimal(4,1)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseTemplateId");

                    b.HasIndex("TrainingId");

                    b.ToTable("ExerciseEntities", "public");
                });

            modelBuilder.Entity("Oid85.Athletic.Infrastructure.Entities.ExerciseTemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("ExerciseTemplateEntities", "public");
                });

            modelBuilder.Entity("Oid85.Athletic.Infrastructure.Entities.PlanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid?>("DayTrainingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MorningTrainingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DayTrainingId");

                    b.HasIndex("MorningTrainingId");

                    b.ToTable("PlanEntities", "public");
                });

            modelBuilder.Entity("Oid85.Athletic.Infrastructure.Entities.PressureEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Dia")
                        .HasColumnType("integer");

                    b.Property<int?>("Pulse")
                        .HasColumnType("integer");

                    b.Property<int>("Sys")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PressureEntities", "public");
                });

            modelBuilder.Entity("Oid85.Athletic.Infrastructure.Entities.TrainingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Cycles")
                        .HasColumnType("integer");

                    b.Property<int?>("FinishCardioMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("StartCardioMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalCountIterations")
                        .HasColumnType("integer");

                    b.Property<double?>("TotalWeight")
                        .HasColumnType("decimal(6,1)");

                    b.HasKey("Id");

                    b.ToTable("TrainingEntities", "public");
                });

            modelBuilder.Entity("Oid85.Athletic.Infrastructure.Entities.ExerciseEntity", b =>
                {
                    b.HasOne("Oid85.Athletic.Infrastructure.Entities.ExerciseTemplateEntity", "ExerciseTemplate")
                        .WithMany()
                        .HasForeignKey("ExerciseTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oid85.Athletic.Infrastructure.Entities.TrainingEntity", "Training")
                        .WithMany("Exercises")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseTemplate");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("Oid85.Athletic.Infrastructure.Entities.PlanEntity", b =>
                {
                    b.HasOne("Oid85.Athletic.Infrastructure.Entities.TrainingEntity", "DayTraining")
                        .WithMany()
                        .HasForeignKey("DayTrainingId");

                    b.HasOne("Oid85.Athletic.Infrastructure.Entities.TrainingEntity", "MorningTraining")
                        .WithMany()
                        .HasForeignKey("MorningTrainingId");

                    b.Navigation("DayTraining");

                    b.Navigation("MorningTraining");
                });

            modelBuilder.Entity("Oid85.Athletic.Infrastructure.Entities.TrainingEntity", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
