// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oid85.Athletic.Infrastructure;

#nullable disable

namespace Oid85.Athletic.Infrastructure.Migrations
{
    [DbContext(typeof(AthleticContext))]
    [Migration("20251105131205_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityAlwaysColumns(modelBuilder);

            modelBuilder.Entity("Oid85.Athletic.Infrastructure.Entities.ExerciseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("CountIterations")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExerciseTemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TrainingEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrainingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseTemplateId");

                    b.HasIndex("TrainingEntityId");

                    b.HasIndex("TrainingId");

                    b.ToTable("exercises", "public");
                });

            modelBuilder.Entity("Oid85.Athletic.Infrastructure.Entities.ExerciseTemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("exercise_templates", "public");
                });

            modelBuilder.Entity("Oid85.Athletic.Infrastructure.Entities.PlanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("DayTrainingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MorningTrainingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DayTrainingId");

                    b.HasIndex("MorningTrainingId");

                    b.ToTable("plans", "public");
                });

            modelBuilder.Entity("Oid85.Athletic.Infrastructure.Entities.TrainingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("CountCycles")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("trainings", "public");
                });

            modelBuilder.Entity("Oid85.Athletic.Infrastructure.Entities.ExerciseEntity", b =>
                {
                    b.HasOne("Oid85.Athletic.Infrastructure.Entities.ExerciseTemplateEntity", "ExerciseTemplate")
                        .WithMany()
                        .HasForeignKey("ExerciseTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oid85.Athletic.Infrastructure.Entities.TrainingEntity", null)
                        .WithMany("Exercises")
                        .HasForeignKey("TrainingEntityId");

                    b.HasOne("Oid85.Athletic.Infrastructure.Entities.TrainingEntity", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseTemplate");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("Oid85.Athletic.Infrastructure.Entities.PlanEntity", b =>
                {
                    b.HasOne("Oid85.Athletic.Infrastructure.Entities.TrainingEntity", "DayTraining")
                        .WithMany()
                        .HasForeignKey("DayTrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oid85.Athletic.Infrastructure.Entities.TrainingEntity", "MorningTraining")
                        .WithMany()
                        .HasForeignKey("MorningTrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DayTraining");

                    b.Navigation("MorningTraining");
                });

            modelBuilder.Entity("Oid85.Athletic.Infrastructure.Entities.TrainingEntity", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
